### PR TITLE
Fix possible null dereference.

### PR DESCRIPTION
**Pull request by chestnykh**
strace.c:
- `filename` pointer has dereferenced many times earlier so the check that filename is not NULL doesn't needed.
- current_tcp pointer must be checked before each dereferencing

### CODE REVIEW

**Review by ldv-alt — CHANGES_REQUESTED** [review]
According to tests, when this change is applied, strace aborts with `free(): invalid pointer` diagnostics.

**Comment by chestnykh** [comment]
Yes, i've realized that the memory allocated in `expand_tcbtab` shouldn't be freed at the end of this function because it is references later

**Comment by chestnykh** [comment]
Hmm, looks like last CI run got not last revision

**Comment by ldv-alt** [comment]
> Hmm, looks like last CI run got not last revision

Do you suppose github is capable of doing that kind of things?

**Comment by chestnykh** [comment]
I don't know
I will close this PR and create new one :)

**Pull request closed without merging**
