### PR TITLE
INSTALL: mention bootstrap script

### PR DESCRIPTION
**Pull request by dvyukov**
It's bootstrap that generates xlat and configure.
Without bootstrap nothing works.
Mention that it needs to be run as the first step.

### CODE REVIEW

**Comment by haoyouab** [comment]
Actually there is a file INSTALL-git.md that mentions bootstrap script. People usually miss it, though.

**Comment by dvyukov** [comment]
Right!
I missed it because based on its size it looked like a forwarding reference to INSTALL, which looks like real instructions. And since I've found what looks like instruction for building from source, I did not expect that there are some other instructions for building from some other source.
What is INSTALL for then?

**Comment by ldv-alt** [comment]
We still support installing strace from release tarballs as well as from the git repository.
Unfortunately, we are not very good at separating documentation relevant for git repository users from the rest of documentation, but we are getting better.

For now, please start with README.md which in turn references INSTALL-git.md file.

**Comment by dvyukov** [comment]
OK

**Comment by dvyukov** [comment]
Maybe it makes sense to merge the 2 docs, but say something like `Step 0. run ./bootstrap (skip if you are using a release tarball and already have configure)` to eliminate the documentation indirection for users.

**Pull request closed without merging**
