### PR TITLE
Print SELinux contexts when enabling "--secontext" (not compatible with "-c").

### PR DESCRIPTION
**Pull request by rmetrich**
This is very useful when debugging SELinux issues, in particular when a process runs in an unexpected context or didn't transition properly, or typically when a file being opened has not the proper context.

Sub-option `--typeonly` may be used to only print the type, as shown in the examples below:

Without any option (standard strace, here used `-fttTvyy` flags):
~~~
118104  16:52:11.141122 select(9, [4<TCP:[0.0.0.0:22]> 6<TCPv6:[[::]:22]>], NULL, NULL, NULL) = 1 (in [4]) <1.845416>
119820  16:52:13.133319 openat(AT_FDCWD, "/home/rmetrich/.ssh/authorized_keys", O_RDONLY|O_NONBLOCK) = 11</home/rmetrich/.ssh/authorized_keys> <0.000399>
~~~

With `--secontext` option, a new column is added after PID, showing the context the PID is executing and each PATH has its context associated (when file exists) :
~~~
118104 [system_u:system_r:sshd_t:s0-s0:c0.c1023] 16:52:11.141122 select(9, [4<TCP:[0.0.0.0:22]> 6<TCPv6:[[::]:22]>], NULL, NULL, NULL) = 1 (in [4]) <1.845416>
119820 [system_u:system_r:sshd_t:s0-s0:c0.c1023] 16:52:13.133319 openat(AT_FDCWD, "/home/rmetrich/.ssh/authorized_keys" [system_u:object_r:nfs_t:s0], O_RDONLY|O_NONBLOCK) = 11</home/rmetrich/.ssh/authorized_keys> [system_u:object_r:nfs_t:s0] <0.000399>
~~~

With `--typeonly` sub-option, same except only the type is displayed:
~~~
118104 [sshd_t] 16:52:11.141122 select(9, [4<TCP:[0.0.0.0:22]> 6<TCPv6:[[::]:22]>], NULL, NULL, NULL) = 1 (in [4]) <1.845416>
119820 [sshd_t] 16:52:13.133319 openat(AT_FDCWD, "/home/rmetrich/.ssh/authorized_keys" [nfs_t], O_RDONLY|O_NONBLOCK) = 11</home/rmetrich/.ssh/authorized_keys> [nfs_t] <0.000399>
~~~

### CODE REVIEW

**Comment by rmetrich** [comment]
Hello @ldv-alt , by the way your talks at Decvonf were great :-)

The CI is failing for some weird reason: I'm now linking with `-ldl` added to Makefile.am but this fails on line 3016 (e.g. https://travis-ci.org/strace/strace/jobs/643826833?utm_medium=notification&utm_source=github_status):
~~~
gcc -m32 -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings -Werror   -g -O2 -ldl ...
~~~

The `-ldl` is specified, but apparently symbols are not there:
~~~
/home/travis/build/strace/strace/strace-5.4.0.87.4c3c/_build/sub/../../strace.c:2023: undefined reference to `dlopen'
/home/travis/build/strace/strace/strace-5.4.0.87.4c3c/_build/sub/../../strace.c:2025: undefined reference to `dlsym'
/home/travis/build/strace/strace/strace-5.4.0.87.4c3c/_build/sub/../../strace.c:2027: undefined reference to `dlsym'
/home/travis/build/strace/strace/strace-5.4.0.87.4c3c/_build/sub/../../strace.c:2029: undefined reference to `dlsym'
/home/travis/build/strace/strace/strace-5.4.0.87.4c3c/_build/sub/../../strace.c:2030: undefined reference to `dlerror'
/home/travis/build/strace/strace/strace-5.4.0.87.4c3c/_build/sub/../../strace.c:2032: undefined reference to `dlerror'
~~~

I'm no Automake expert, so maybe I just added the lib to wrong place.

**Comment by esyr** [comment]
See also #45.

**Comment by esyr** [comment]
On Thu, Jan 30, 2020 at 03:31:15PM +0000, Renaud Métrich wrote:
> The CI is failing for some weird reason: I'm now linking with `-ldl` added to Makefile.am but this fails on line 3016 (e.g. https://travis-ci.org/strace/strace/jobs/643826833?utm_medium=notification&utm_source=github_status):

If you want to link strace with -ldl, you should add -ldl to strace_LDADD
rather than strace_LDFLAGS, otherwise -ldl will be effectively ignored on
systems where ld --as-needed is enabled by default.

**Comment by rmetrich** [comment]
Hello @esyr , it appears that the travis CI fails randomly for some architecture (always different) in code that I didn't touch at all, is travis CI really robust?
Additionally, seeing that Code coverage decreased, I added some tests (`strace--secontext*`), but these don't run because no environment seems to have SELinux enabled (I'm relying on binary `selinuxenabled`).

**Comment by rmetrich** [comment]
@esyr @ldv-alt Hi,
I'm proposing this PR to be able to have information on SELinux contexts, which is very useful for my daily job (maintenance eng. at Red Hat).
I've submitted unit tests as well but apparently the CI doesn't run SELinux since I get reduced code coverage error, although running `make check-code-coverage` locally on my Fedora system shows my code being covered.

**Comment by parport0** [comment]
For reference, review of this PR is being done in the mailing list, starting [here](https://lists.strace.io/pipermail/strace-devel/2020-November/010266.html), and most recently discussed [here](https://lists.strace.io/pipermail/strace-devel/2021-February/010402.html).

**Comment by ldv-alt** [comment]
Implemented in commit e921913eecd5025dae688fdf9c365023fe3b8a0c.

**Pull request closed without merging**
