### PR TITLE
unwind-libdw: add -kk/--stack-traces=+source option

### PR DESCRIPTION
**Pull request by masatake**
This change adds source code information to stack traces printed with -k option if strace links to libdw.

An example output:
```
    exit_group(0)                           = ?
    +++ exited with 0 +++
     > /usr/lib64/libc.so.6(_exit+0x1d) [0xdb44d] ../sysdeps/unix/sysv/linux/_exit.c:30
     > /usr/lib64/libc.so.6(__run_exit_handlers+0x125) [0x40165] /usr/src/debug/glibc-2.37-4.fc38.x86_64/stdlib/exit.c:134
     > /usr/lib64/libc.so.6(exit+0x1d) [0x402ed] /usr/src/debug/glibc-2.37-4.fc38.x86_64/stdlib/exit.c:141
     > /usr/lib64/libc.so.6(__libc_start_call_main+0x80) [0x27b50] ../sysdeps/nptl/libc_start_call_main.h:74
     > /usr/lib64/libc.so.6(__libc_start_main@@GLIBC_2.34+0x8a) [0x27c0a] ../csu/libc-start.c:360
     > /usr/bin/ls(_start+0x24) [0x6d54]
```
* NEWS: Mention this.
* doc/strace.1.in: Document this.
* src/defs.h (stack_trace_modes): New enum. (stack_trace_modes::STACK_TRACE_OFF,STACK_TRACE_ON, STACK_TRACE_WITH_SRCINFO): New enumerators.
(stack_trace_enabled): Rename this variabel declaration to... (stack_trace_mode): ... this. The type is also changed from bool to enum stack_trace_modes.
(unwind_init): Add a bool parameter.
* src/filter_seccomp.c (traced_by_seccomp): Use the new variable name, stack_trace_mode.
* src/strace.c (stack_trace_enabled): Rename this variabel to... (stack_trace_mode): ... this.
[ENABLE_STACKTRACE]/[USE_LIBDW] (K_OPT): Add "kk" option. [ENABLE_STACKTRACE] (usage): Print --stack-traces=symbol options. [ENABLE_STACKTRACE]/[USE_LIBDW] (usage): Print -kk and --strack-traces=+source options.
[ENABLE_STACKTRACE] (after_successful_attach): Use the new variable name, stack_trace_mode.
(GETOPT_STACK): New enumerator.
(init::longopts): Let --stack-traces take an option argument. Use GETOPT_STACK as the val for --stack-traces.
[ENABLE_STACKTRACE] (init): Handle -kk and --stack-traces=+source options.
(init): Forbid to use -kk/--stack-traces=+source and -c/--summary-only together.
(init): Pass ture to unwind_init() if -kk or --stack-traces=+source is given.
(print_stopped): Use the new variable
name, stack_trace_mode.
* src/syscall.c (update_personality): Use the new variable name, stack_trace_mode.
(syscall_entering_trace): Ditto.
(syscall_exiting_trace): Ditto.
* src/unwind.h (unwind_call_action_fn): add parameters source_filename and source_line as parameters.
(struct unwind_unwinder_t::init): Add a bool parameter.
* src/unwind.c (unwind_init): Add with_srcinfo parameter and pass it to init method of backend.
(STACK_ENTRY_SYMBOL_WITH_SRCINFO_FMT): New format string for printing stack trace entries with source code information. (print_call_cb): Add source_filename and source_line as parameters. Build stack trace entries with
STACK_ENTRY_SYMBOL_WITH_SRCINFO_FMT if source_filename is given. (queue_put): Add source_filename and source_line as parameters. Pass them to sprint_call_or_error().
(queue_put_call): Do the same as queue_put.
(queue_put_error): Pass NULL as source_filename, 0 as source_line to queue_put().
* src/unwind-libdw.c (struct cache_entry::source_filename, struct cache_entry::source_line): New members.
(with_srcinfo): New file local variable.
(init): Set with_srcinfo.
(frame_callback): Get source information for pc from dwfl_module_getsrc() and dwfl_lineinfo().  Pass the source information to call_action method and fill the source_filename and source_line members of cache entry.
* src/unwind-libunwind.c (init, print_stack_frame): Adjust the code to the updated interface declared in unwind.h.
* tests/Makefile.am (check_SCRIPTS): add strace-kk.test. (check_DATA): strace-kk.expected.
[ENABLE_STACKTRACE]/[USE_LIBDW] (STACKTRACE_TESTS): add strace-kk.test.
* tests/strace-k.test: Add KOPT_SHORT and KOPT_LONG variables to make the test case reusable for testing -kk option. Don't hardcode -k and --stack-traces. Refine the pattern passed to awk; make the original pattern more specific for testing only -k/--stack-traces=symbol option, and add a new pattern for testing -kk/--stack-traces=+source.
* tests/strace-kk.expected: New file.
* tests/strace-kk.test: New test case.

### CODE REVIEW

**Comment by masatake** [comment]
It seems that stace -kk doesn't show the source information only when a target is built with clang. I must talk about this to the developers of libdw.

**Comment by masatake** [comment]
I got an answer about the clang issue on the bugzilla entry: -gdwarf-aranges should be passed to clang. I will update this pull request.

**Comment by masatake** [comment]
The errors reported from CI/CD checks are not related to this pull request.

**Comment by masatake** [comment]
I submitted this changes to the strace-devel list.

**Comment by masatake** [comment]
The review result: https://lists.strace.io/pipermail/strace-devel/2023-November/011372.html .

**Comment by ldv-alt** [comment]
> The errors reported from CI/CD checks are not related to this pull request.

Even though the CI regression is completely unrelated to this PR, you might have better understanding what's the issue behind it and what could be a workaround.  These CI errors are new, they happen consistently on x32 runners, and the failing test is ioctl_kvm_run_auxstr_vcpu:
```
--- exp	2023-11-20 06:19:59.114039139 +0000
+++ out	2023-11-20 06:19:59.114039139 +0000
@@ -12,6 +12,6 @@
 ioctl(5<anon_inode:kvm-vcpu:0>, KVM_GET_SREGS, {cs={base=0xffff0000, limit=65535, selector=61440, type=10, present=1, dpl=0, db=0, s=1, l=0, g=0, avl=0}, ...}) = 0
 ioctl(5<anon_inode:kvm-vcpu:0>, KVM_SET_SREGS, {cs={base=0, limit=65535, selector=0, type=10, present=1, dpl=0, db=0, s=1, l=0, g=0, avl=0}, ...}) = 0
 ioctl(5<anon_inode:kvm-vcpu:0>, KVM_SET_REGS, {rax=0x2, ..., rsp=0, rbp=0, ..., rip=0x1000, rflags=0x2}) = 0
-ioctl(5<anon_inode:kvm-vcpu:0>, KVM_RUN, 0) = 0 (KVM_EXIT_IO)
-ioctl(5<anon_inode:kvm-vcpu:0>, KVM_RUN, 0) = 0 (KVM_EXIT_HLT)
+ioctl(5<anon_inode:kvm-vcpu:0>, KVM_RUN, 0) = 0
+ioctl(5<anon_inode:kvm-vcpu:0>, KVM_RUN, 0) = 0
 +++ exited with 0 +++
```

**Review by ldv-alt — APPROVED** [review]

**Pull request merged**
