### PR TITLE
Update bpf syscall decoding

### PR DESCRIPTION
**Pull request by qmonnet**
* bpf.c: Add decoding for BPF_OBJ_PIN, BPF_OBJ_GET, BPF_PROG_ATTACH,
and BPF_PROG_DETACH commands.
* configure.ac: Add checks for BPF features.
* xlat/bpf_attach_type.in: New file.
* xlat/bpf_commands.in: Update list of BPF_* command constants.
* xlat/bpf_map_types.in: Update list of BPF_MAP_TYPE_* constants.
* xlat/bpf_prog_types.in: Update list of BPF_PROG_TYPE_* constants.
* tests/bpf.c: New tests.

### CODE REVIEW

**Comment by qmonnet** [comment]
Hmm I had not realized that there were no other pull requests on the GitHub mirror. Can you merge from here, or should I submit the PR somewhere else? (I should create an account on Sourceforge and send it there maybe?)

**Comment by lineprinter** [comment]
You should submit it to strace-devel@lists.sourceforge.net.

**Comment by qmonnet** [comment]
Ok, will do, thanks!

**Comment by qmonnet** [comment]
[ Follow-up: posted [there](https://sourceforge.net/p/strace/mailman/message/35628208/). ]

**Pull request closed without merging**
